
version: '3.9'
services:
  isaaclab_unitree_g1:
    build: .
    container_name: isaaclab_unitree_g1
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    ports:
      - "8080:8080"
    volumes:
      - ./workspace:/workspace
    tty: true
